// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManagerApi.Data;

#nullable disable

namespace TaskManagerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204104541_FixUserTaskRelationship")]
    partial class FixUserTaskRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManagerApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanAssignTasks")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanCreateTasks")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanCreateUsers")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDeleteTasks")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDeleteUsers")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEditAllTasks")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEditUsers")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanExportData")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManagePermissions")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageRoles")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanViewAllTasks")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanViewAllUsers")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanViewReports")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanAssignTasks = true,
                            CanCreateTasks = true,
                            CanCreateUsers = true,
                            CanDeleteTasks = true,
                            CanDeleteUsers = true,
                            CanEditAllTasks = true,
                            CanEditUsers = true,
                            CanExportData = true,
                            CanManagePermissions = true,
                            CanManageRoles = true,
                            CanViewAllTasks = true,
                            CanViewAllUsers = true,
                            CanViewReports = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system administrator with all permissions",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CanAssignTasks = true,
                            CanCreateTasks = true,
                            CanCreateUsers = true,
                            CanDeleteTasks = true,
                            CanDeleteUsers = false,
                            CanEditAllTasks = true,
                            CanEditUsers = true,
                            CanExportData = true,
                            CanManagePermissions = false,
                            CanManageRoles = false,
                            CanViewAllTasks = true,
                            CanViewAllUsers = true,
                            CanViewReports = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Department director with extensive permissions",
                            Name = "Director"
                        },
                        new
                        {
                            Id = 3,
                            CanAssignTasks = true,
                            CanCreateTasks = true,
                            CanCreateUsers = true,
                            CanDeleteTasks = true,
                            CanDeleteUsers = false,
                            CanEditAllTasks = true,
                            CanEditUsers = true,
                            CanExportData = false,
                            CanManagePermissions = false,
                            CanManageRoles = false,
                            CanViewAllTasks = true,
                            CanViewAllUsers = true,
                            CanViewReports = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Division manager with task and user management for their division",
                            Name = "Division"
                        },
                        new
                        {
                            Id = 4,
                            CanAssignTasks = false,
                            CanCreateTasks = true,
                            CanCreateUsers = false,
                            CanDeleteTasks = false,
                            CanDeleteUsers = false,
                            CanEditAllTasks = false,
                            CanEditUsers = false,
                            CanExportData = false,
                            CanManagePermissions = false,
                            CanManageRoles = false,
                            CanViewAllTasks = false,
                            CanViewAllUsers = false,
                            CanViewReports = false,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Regular user with basic task management",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("TaskManagerApi.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualHours")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstimatedHours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DueDate");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Description = "Initialize the project with proper folder structure",
                            DueDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Priority = "High",
                            Status = "Completed",
                            Title = "Setup Project Structure"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Description = "Add JWT authentication to the API",
                            DueDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Priority = "High",
                            Status = "In Progress",
                            Title = "Implement Authentication"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Description = "Build the main dashboard for task management",
                            DueDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Priority = "Medium",
                            Status = "Pending",
                            Title = "Create Task Dashboard"
                        },
                        new
                        {
                            Id = 4,
                            CompletedAt = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 2,
                            Description = "Create and run database migrations",
                            DueDate = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Priority = "High",
                            Status = "Completed",
                            Title = "Database Migration"
                        });
                });

            modelBuilder.Entity("TaskManagerApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@taskmanager.com",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "admin123",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "director@taskmanager.com",
                            FullName = "John Director",
                            IsActive = true,
                            PasswordHash = "director123",
                            RoleId = 2,
                            Username = "director"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "division@taskmanager.com",
                            FullName = "Sarah Division",
                            IsActive = true,
                            PasswordHash = "division123",
                            RoleId = 3,
                            Username = "division"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@taskmanager.com",
                            FullName = "Regular User",
                            IsActive = true,
                            PasswordHash = "user123",
                            RoleId = 4,
                            Username = "user"
                        });
                });

            modelBuilder.Entity("TaskUsers", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TaskId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskUsers");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            UserId = 1,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TaskId = 2,
                            UserId = 2,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TaskId = 3,
                            UserId = 3,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TaskId = 4,
                            UserId = 4,
                            AssignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TaskId = 1,
                            UserId = 2,
                            AssignedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            TaskId = 2,
                            UserId = 3,
                            AssignedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TaskManagerApi.Models.TaskItem", b =>
                {
                    b.HasOne("TaskManagerApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TaskManagerApi.Models.User", b =>
                {
                    b.HasOne("TaskManagerApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaskUsers", b =>
                {
                    b.HasOne("TaskManagerApi.Models.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagerApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManagerApi.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
